name: Lint
on: [pull_request]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          tools: composer
          coverage: none

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache PHP dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Cache node modules
        id: cache
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('**/package-lock.json') }}

      - name: Install PHP dependencies
        run: composer install --prefer-dist

      - name: Install JS dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install

      - name: Install reviewdog
        uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest

      - name: Lint styles
        uses: reviewdog/action-stylelint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          stylelint_input: '**/*.scss'
          fail_on_error: true
        if: always()

      - name: Lint scripts
        uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          fail_on_error: true
        if: always()

      - name: Lint PHP
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: php ./vendor/bin/phpcs --report=diff -- $(git diff --name-only --diff-filter=ACMR origin/master | grep \\.php | xargs) | sed -r 's/[[:cntrl:]]\[[0-9]{1,3}m//g' | sed -E 's/--- (.+)$/\0\n+++ \1/g; /\+\+\+ PHP_CodeSniffer$/d' | reviewdog -f=diff -f.diff.strip=0 -name=phpcs -reporter=github-pr-review -filter-mode=nofilter -fail-on-error
        if: always()
